### PR TITLE
Replace BIND9 with DNSmasq

### PR DESCRIPTION
**Pull request by zerlgi**
Hi Jorge

This pull-request is primarily a suggestion. I replaced BIND9 with DNSmasq for the following reasons:

Dnsmasq is smaller, less requirements, and allows replacement of individual DNS records without needing to control an entire domain
e.g
Return an MX record named "maildomain.com" with target
servermachine.com and preference 50
''mx-host=maildomain.com,servermachine.com,50''

### CODE REVIEW

**Comment by jorgedlcruz** [comment]
Hi zerigi,
The idea is merge both, and offer like an option to the users, like ./ZimbraEasyInstall {DOMAIN} {IP} {ZIMBRAPASS} {BIND or DNSMASQ} 
So I will take you code and merge with the main one with this new option, what do you think?

Thank you

**Comment by zerlgi** [comment]
Hi Jorge

That sounds great (to have the two options)

Regards
Z

**Comment by barrydegraaff** [comment]
I prefer dnsmasq for this.

**Comment by barrydegraaff** [comment]
1:22:04 PM - Jorge-zimb: Close it, as the idea is good, but it's better to include it like a feature, so people can deploy dnsmasq or bind, per default bind if people don't say other thing.

So we cannot accept this PR for now.

**Pull request closed without merging**
